jetstream {}

debug: true
trace: true

tls {
  cert_file: "/Users/shuryakumar.ns/Downloads/spiffe/server-cert.pem"
  key_file:  "/Users/shuryakumar.ns/Downloads/spiffe/server-key.pem"
  ca_file:   "/Users/shuryakumar.ns/Downloads/spiffe/rootCA-cert.pem"
  verify_and_map: true
}

accounts {
  NDB: {
    jetstream: enabled
    users: [
      { user: "CN=auth_service" }
    ]
  }
  SYS: {}
}
system_account: SYS

authorization {
  auth_callout {
    issuer: AAGNUDSFGGGA4T6LUBC2JALBOARYO3N67REMZEJDNUSYQP2WJHIRAI2X
    auth_users: [ "CN=auth_service" ]
    account: NDB
  }
}
