jetstream {}

accounts {
  NDB: {
    jetstream: enabled
    users: [
      { user: ndb, password: Nutanix.1 }
    ]
  }
  SYS: {}
}
system_account: SYS

authorization {
  auth_callout {
    issuer: AAGNUDSFGGGA4T6LUBC2JALBOARYO3N67REMZEJDNUSYQP2WJHIRAI2X
    auth_users: [ ndb ]
    account: NDB
  }
}
